name: Events Demo 01
on:
  pull_request:
    types: # single or list like this -> [opened,edited] or like below
      - opened
#       - closed
  workflow_dispatch: # or use multiple triggers
  push:
    branches: # filters
      - main
      - dev
      - 'dev-*'   # dev-new, dev-user-new
      - 'feat/**'  # feat/dev, feat/user/dev, etc
jobs:
  DeployJob:
    runs-on: ubuntu-latest
    steps: 
      - name: Output event data step
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code step
        uses: actions/checkout@v4
      - name: Install dependencies step
        run: npm ci
      - name: Lint step
        run: npm run lint
      - name: Test code step
        run: npm run test
      - name: Build project step
        run: npm run build
      - name: Deploy code step
        run: echo "Deploying..."